cache: pip

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - os: linux
      dist: xenial
      python: "3.7"
      env: TOXENV=py37
      sudo: true
    - python: "3.5"
      env: TOXENV=lint
    - if: branch = master AND type = push
      os: linux
      dist: xenial
      python: "3.7"
      sudo: true
      script: deploy_documentation.sh
      git:
        depth: false

before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_xxxxxxxxxxxx_key
    -iv $encrypted_xxxxxxxxxxxx_iv
    -in github_deploy_key.enc
    -out github_deploy_key
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
