matrix:
  fast_finish: true
  include:
    - if: branch = master AND type = push
      os: linux
      dist: xenial
      python: "3.7"
      sudo: true
      script: ./deploy_documentation.sh
      git:
        depth: false

before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_43156c1f40d1_key
    -iv $encrypted_43156c1f40d1_iv
    -in github_deploy_key.enc
    -out github_deploy_key
    -d
  - chmod 777 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
